// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/cart_service.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gin "github.com/gin-gonic/gin"
	gomock "github.com/golang/mock/gomock"
)

// MockCartServiceInterface is a mock of CartServiceInterface interface.
type MockCartServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockCartServiceInterfaceMockRecorder
}

// MockCartServiceInterfaceMockRecorder is the mock recorder for MockCartServiceInterface.
type MockCartServiceInterfaceMockRecorder struct {
	mock *MockCartServiceInterface
}

// NewMockCartServiceInterface creates a new mock instance.
func NewMockCartServiceInterface(ctrl *gomock.Controller) *MockCartServiceInterface {
	mock := &MockCartServiceInterface{ctrl: ctrl}
	mock.recorder = &MockCartServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCartServiceInterface) EXPECT() *MockCartServiceInterfaceMockRecorder {
	return m.recorder
}

// AddItemToCart mocks base method.
func (m *MockCartServiceInterface) AddItemToCart(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddItemToCart", c)
}

// AddItemToCart indicates an expected call of AddItemToCart.
func (mr *MockCartServiceInterfaceMockRecorder) AddItemToCart(c interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddItemToCart", reflect.TypeOf((*MockCartServiceInterface)(nil).AddItemToCart), c)
}

// DeleteCartItem mocks base method.
func (m *MockCartServiceInterface) DeleteCartItem(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DeleteCartItem", c)
}

// DeleteCartItem indicates an expected call of DeleteCartItem.
func (mr *MockCartServiceInterfaceMockRecorder) DeleteCartItem(c interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCartItem", reflect.TypeOf((*MockCartServiceInterface)(nil).DeleteCartItem), c)
}

// GetCartData mocks base method.
func (m *MockCartServiceInterface) GetCartData(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GetCartData", c)
}

// GetCartData indicates an expected call of GetCartData.
func (mr *MockCartServiceInterfaceMockRecorder) GetCartData(c interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCartData", reflect.TypeOf((*MockCartServiceInterface)(nil).GetCartData), c)
}
